# Generated by Django 5.0.1 on 2024-01-10 18:40

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ITO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=25, null=True, verbose_name="Nombre"),
                ),
                (
                    "mobil",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="Movil"
                    ),
                ),
                (
                    "correo",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="email"
                    ),
                ),
                (
                    "rut",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="RUT"
                    ),
                ),
            ],
            options={
                "verbose_name": "ITO",
                "verbose_name_plural": "ITOs",
            },
        ),
        migrations.CreateModel(
            name="PdfFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, editable=False, max_length=100)),
                (
                    "pdf",
                    models.FileField(
                        storage=main.models.OverwriteStorage(), upload_to="pdfs/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sitio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cod",
                    models.CharField(
                        max_length=10, null=True, verbose_name="Codigo Sitio"
                    ),
                ),
                (
                    "comuna",
                    models.CharField(blank=True, max_length=30, verbose_name="Comuna"),
                ),
                (
                    "altura",
                    models.IntegerField(
                        choices=[(24, "24"), (42, "42"), (48, "48")],
                        default=42,
                        verbose_name="Altura",
                    ),
                ),
                (
                    "contratista",
                    models.CharField(
                        choices=[("MER", "MER"), ("AJ", "AJ")],
                        default="MER",
                        max_length=120,
                        verbose_name="Contratista",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ASG", "Asignado"),
                            ("EJE", "Ejecución"),
                            ("TER", "Terminado"),
                            ("PTG", "Postergado"),
                            ("CAN", "Cancelado"),
                        ],
                        default="EJE",
                        max_length=10,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "lat",
                    models.FloatField(
                        blank=True, max_length=10, null=True, verbose_name="Latitud"
                    ),
                ),
                (
                    "lon",
                    models.FloatField(
                        blank=True, max_length=10, null=True, verbose_name="Longitud"
                    ),
                ),
                (
                    "hormigonado",
                    models.BooleanField(default=False, verbose_name="Hor."),
                ),
                ("montado", models.BooleanField(default=False, verbose_name="Mon.")),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descripción"
                    ),
                ),
                ("avance", models.IntegerField(default=0, verbose_name="%")),
                (
                    "ito",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.ito",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sitio",
                "verbose_name_plural": "Sitios",
            },
        ),
    ]
