# Generated by Django 5.0.1 on 2024-01-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitio",
            name="empalmeE",
            field=models.BooleanField(default=False, verbose_name="Ele."),
        ),
    ]
