# Generated by Django 5.0.1 on 2024-01-18 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_sitio_fechafin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitio",
            name="fechaFin",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Fecha"
            ),
        ),
    ]
